# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libhdf5-openmpi-dev trilinos-dev
        pip install numpy scipy matplotlib docutils mpi4py pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout amuse repo
      uses: actions/checkout@v2
      with:
        repository: amusecode/amuse
        path: amuse        
    - name: Checkout omuse repo
      uses: actions/checkout@v2
      with:
        repository: omuse-geoscience/omuse
        path: omuse
        ref: smcm
# install amuse manually to get latest
    - name: Install amuse
      run: |
        cd amuse/packages/amuse-framework
        pip install -e .
    - name: Install omuse
      run: |
        cd omuse
        pip install -e .
    - name: check installation
      run: |
        amusifier --get-amuse-configmk
        pip list
    - name: build iemic
      run: |
        cd omuse/src/omuse/community/iemic
        make DOWNLOAD_CODES=1
        
